server:
  port: 8080

jwt:
  secret: zluteprasatkoslodolesa585858.

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method
    path: /api-docs-ui.html

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/etoro
    username: postgres
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  devtools:
    livereload:
      enabled: true
